Repository microsoft/CLOG, pull requests merged in 2020-08, with the labels that each got.

#35 Feature/0.1.4
  README.md
  clog/CommandLineArguments.cs
  clog/TraceEmitterModules/CLogLTTNGOutputModule.cs
  clog/clog.cs
  clog/clog.csproj
  clog2text/clog2text_lttng/clog2text_lttng.csproj
  clog2text/clog2text_windows/clog2text_windows.csproj
  clogutils/CLogFileProcessor.cs
  clogutils/CLogFullyDecodedMacroEmitter.cs
  clogutils/CLogHandledException.cs
  clogutils/CLogSidecar.cs
  defaults/defaults.clog.cs
Labels: bug, documentation, enhancement

#46 Switch warnings to errors in clog build, fix warning
  clog/clog.csproj
  clog2text/clog2text_lttng/clog2text_lttng.csproj
  clog2text/clog2text_windows/clog2text_windows.csproj
  clogutils/CLogHandledException.cs
  clogutils/clogutils.csproj
Labels: build

#49 Allow unsafe for the custom decoders
  clogutils/CLogCustomTraceEmittorFactory.cs
Labels: enhancement

#50 Add config file as a clog dependency, and also a way to add extra dependencies to clog generation
  defaults/CLog.cmake
Labels: build

#52 Feature/0.1.6
  clog/TraceEmitterModules/CLogSTDOUT.cs
  clog/clog.cs
  clog/clog.csproj
  clog2text/clog2text_lttng/clog2text_lttng.csproj
  clog2text/clog2text_windows/clog2text_windows.csproj
  clogutils/CLogFileProcessor.cs
  clogutils/CLogFullyDecodedMacroEmitter.cs
  clogutils/CLogSidecar.cs
Labels: bug, enhancement, sidecar

#54 Nuke Revisions in Readme
  README.md
Labels: documentation

#55 Readme Touch ups
  README.md
Labels: documentation

#56 Source Tree Clean Up
  .azure/azure-pipelines.ci.yml
  .github/CODE_OF_CONDUCT.md
  .github/SECURITY.md
  NuGet.config
  clog.sln
  src/clog/CommandLineArguments.cs
  src/clog/TraceEmitterModules/CLogDTraceOutputModule.cs
  src/clog/TraceEmitterModules/CLogLTTNGOutputModule.cs
  src/clog/TraceEmitterModules/CLogManifestedETWOutputModule.cs
  src/clog/TraceEmitterModules/CLogSTDOUT.cs
  src/clog/TraceEmitterModules/CLogSysLog.cs
  src/clog/TraceEmitterModules/CLogSystemTapModule.cs
  src/clog/TraceEmitterModules/CLogTraceLoggingOutputModule.cs
  src/clog/clog.cs
  src/clog/clog.csproj
  src/clog2text/clog2text_lttng/CommandLineArguments.cs
  src/clog2text/clog2text_lttng/Program.cs
  src/clog2text/clog2text_lttng/clog2text_lttng.csproj
  src/clog2text/clog2text_windows/App.config
  src/clog2text/clog2text_windows/CommandLineArguments.cs
  src/clog2text/clog2text_windows/Program.cs
  src/clog2text/clog2text_windows/clog2text_windows.csproj
  src/clogutils/CLogConsoleTrace.cs
  src/clogutils/CLogCustomTraceEmittorFactory.cs
  src/clogutils/CLogDecodedTraceLine.cs
  src/clogutils/CLogEncodingCLogTypeSearch.cs
  src/clogutils/CLogEncodingType.cs
  src/clogutils/CLogEnterReadOnlyModeException.cs
  src/clogutils/CLogErrors.cs
  src/clogutils/CLogFileProcessor.cs
  src/clogutils/CLogFullyDecodedMacroEmitter.cs
  src/clogutils/CLogHandledException.cs
  src/clogutils/CLogLineMatch.cs
  src/clogutils/CLogSidecar.cs
  src/clogutils/CLogTypeNotFoundException.cs
  src/clogutils/CLogTypeSearchNode.cs
  src/clogutils/ConfigFile/CLogConfigurationFile.cs
  src/clogutils/ConfigFile/CLogModuleUsageInformation.cs
  src/clogutils/ConfigFile/CLogTraceLineInformation.cs
  src/clogutils/ConfigFile/CLogTypeEncoder.cs
  src/clogutils/ICLogOutputModule.cs
  src/clogutils/MacroDefinations/CLogConfigurationProfile.cs
  src/clogutils/MacroDefinations/CLogExportModuleDefination.cs
  src/clogutils/MacroDefinations/CLogTraceMacroDefination.cs
  src/clogutils/MacroDefinations/CLogUniqueIDEncoder.cs
  src/clogutils/clogutils.csproj
  src/converters/syslog2clog/CommandLineArguments.cs
  src/converters/syslog2clog/syslog2clog.cs
  src/converters/syslog2clog/syslog2clog.csproj
  src/decoderTest/Program.cs
  src/decoderTest/decoderTest.csproj
Labels: build

#58 Fixes .NET references for compiled decoder, runs decoder during build
  .gitignore
  src/clog/clog.cs
  src/clog/clog.csproj
  src/clog2text/clog2text_lttng/clog2text_lttng.csproj
  src/clog2text/clog2text_windows/clog2text_windows.csproj
  src/clogutils/CLogCustomTraceEmittorFactory.cs
  src/clogutils/CodeDomHelper/Extensions.cs
  src/clogutils/CodeDomHelper/Generated.cs
  src/clogutils/CodeDomHelper/Generated.targets
  src/clogutils/CodeDomHelper/ResourceLoader.cs
  src/clogutils/CodeDomHelper/TargetFramework.cs
  src/clogutils/ConfigFile/CLogConfigurationFile.cs
  src/clogutils/ConfigFile/CLogTypeEncoder.cs
  src/clogutils/clogutils.csproj
  src/decoderTest/decoderTest.csproj
Labels: bug, decode, enhancement

#59 Ensure any files that are serialized have normalized line endings
  src/clogutils/CLogFileProcessor.cs
  src/clogutils/CLogFullyDecodedMacroEmitter.cs
  src/clogutils/ConfigFile/CLogConfigurationFile.cs
  src/converters/syslog2clog/syslog2clog.cs
Labels: bug, enhancement, sidecar

#61 Properly test compile custom decoder when sidecar is actually saved
  src/clogutils/ConfigFile/CLogConfigurationFile.cs
Labels: tests

#62 Properly write character outputs
  defaults/defaults.clog.cs
  defaults/defaults.clog_config
  examples/clogsample/simple.cpp
  src/clogutils/CLogCustomTraceEmittorFactory.cs
Labels: bug, decode
